[package]
name = "tango"
version = "0.3.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
webrtc = "0.4.0"
ggez = "0.7.0"
zstd = "0.11.1+zstd.1.5.2"

[build-dependencies]
bindgen = "0.53.1"
