compatibility = [
  [ "bn6g", "bn6f", "bn6g-soundmod", "bn6f-soundmod" ],
  [ "exe6g", "exe6f", "exe6g-soundmod", "exe6f-soundmod" ],
  [ "bn6g-allstars", "bn6f-allstars" ],
]

[games.bn6f]
title = "MEGAMAN6_FXX"
hooks = "bn6f"
crc32 = "dee6f2a9"

[games.bn6g]
title = "MEGAMAN6_GXX"
hooks = "bn6g"
crc32 = "79452182"

[games.bn6f-soundmod]
title = "MEGAMAN6_FXX"
hooks = "bn6g"
crc32 = "692a4b1d"

[games.bn6g-soundmod]
title = "MEGAMAN6_GXX"
hooks = "bn6g"
crc32 = "d2d5105f"

[games.exe6f]
title = "ROCKEXE6_RXX"
hooks = "exe6f"
crc32 = "2dfb603e"

[games.exe6g]
title = "ROCKEXE6_GXX"
hooks = "exe6g"
crc32 = "6285918a"
