compatibility = [
  [
    "bn6g",
    "bn6f",
    "bn6g-soundmod",
    "bn6f-soundmod",
  ],
  [
    "exe6g",
    "exe6f",
    "exe6g-soundmod",
    "exe6f-soundmod",
    "exe6g-idealexe",
    "exe6f-idealexe",
  ],
  [
    "bn6g-allstars",
    "bn6f-allstars",
  ],
  [
    "bbn6f-v0_1",
    "bbn6g-v0_1",
  ],
]

[games.bn6f]
title = "MEGAMAN6_FXX"
crc32 = "dee6f2a9"
hooks = "bn6f"

[games.bn6g]
title = "MEGAMAN6_GXX"
crc32 = "79452182"
hooks = "bn6g"

[games.bn6f-soundmod]
title = "MEGAMAN6_FXX"
crc32 = "692a4b1d"
hooks = "bn6f"

[games.bn6g-soundmod]
title = "MEGAMAN6_GXX"
crc32 = "d2d5105f"
hooks = "bn6g"

[games.bn6f-allstars]
title = "MEGAMAN6_FXX"
crc32 = "1f22aaf3"
hooks = "bn6f"

[games.bn6g-allstars]
title = "MEGAMAN6_GXX"
crc32 = "9a4ce339"
hooks = "bn6g"

[games.bbn6f-v0_1]
title = "MEGAMAN6_FXX"
crc32 = "8d083638"
hooks = "bn6f"

[games.bbn6g-v0_1]
title = "MEGAMAN6_GXX"
crc32 = "8c860b42"
hooks = "bn6g"

[games.exe6f]
title = "ROCKEXE6_RXX"
crc32 = "2dfb603e"
hooks = "exe6f"

[games.exe6g]
title = "ROCKEXE6_GXX"
crc32 = "6285918a"
hooks = "exe6g"

[games.exe6f-soundmod]
title = "ROCKEXE6_RXX"
crc32 = "37f05be3"
hooks = "exe6f"

[games.exe6g-soundmod]
title = "ROCKEXE6_GXX"
crc32 = "918f091e"
hooks = "exe6g"

[games.exe6f-idealexe]
title = "ROCKEXE6_RXX"
crc32 = "cae274cd"
hooks = "exe6f"

[games.exe6g-idealexe]
title = "ROCKEXE6_GXX"
crc32 = "d1682777"
hooks = "exe6g"
