[keymapping]
up = "Up"
down = "Down"
left = "Left"
right = "Right"
a = "Z"
b = "X"
l = "A"
r = "S"
select = "Back"
start = "Return"

[matchmaking]
connect_addr = "https://mm.tango.murk.land"
[[webrtc.ice_servers]]
urls = ["stun:stun.l.google.com:19302"]

[[webrtc.ice_servers]]
urls = ["stun:stun1.l.google.com:19302"]

[[webrtc.ice_servers]]
urls = ["stun:stun2.l.google.com:19302"]

[[webrtc.ice_servers]]
urls = ["stun:stun3.l.google.com:19302"]

[[webrtc.ice_servers]]
urls = ["stun:stun4.l.google.com:19302"]
