name: release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - target: x86_64-pc-windows-gnu
                      sysroot: /usr/x86_64-w64-mingw32/sys-root
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive

            - run: sudo apt-get update && sudo apt-get install -y mingw-w64

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}

            - run: BINDGEN_EXTRA_CLANG_ARGS="${{ matrix.sysroot }}" cargo build --release --target ${{ matrix.target }}

            - uses: softprops/action-gh-release@v1
